version: 0.11.0-{branch}-{build}

environment:
    NAME_PREFIX: basecamp
    TARGET: i686-pc-windows-msvc
    CHANNEL: stable

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -vV
    - cargo -vV

build: false

cache:
    - target
    - '%USERPROFILE%\.cargo'

build_script: cargo build

test_script:
    - cargo test --verbose --all -- --test-threads=1

after_test:
    - cargo build --release --verbose

artifacts:
    - path: target/release/ctehxk2.dll
      name: ctehxk2.dll

deploy:
    description: ''
    auth_token:
        secure: VeDpNYDNNJvMfdBEgizkRlB/Goejuq3IVt5ltSJ48ZVGJpvxBNEApjHAvTuCsNAk
    provider: GitHub
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
